# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1remMR4ra2I4qnys6sPtTxbTQNmd7Z-1u
"""

import numpy as np
from scipy.stats import norm
import matplotlib
import matplotlib.pyplot as plt

# Parametres de reference du rapport
S0    = 50.0
K     = 50.0
r     = 0.05
sigma = 0.20
T     = 1.0
M     = 100_000

# METHODE DE MONTE-CARLO NAIVE
def price_naive(N, M=M, seed=0):
    rng = np.random.default_rng(seed)
    dt  = T / N
    Z   = rng.standard_normal((M, N))
    incr = (r - 0.5 * sigma**2) * dt + sigma * np.sqrt(dt) * Z
    logS = np.log(S0) + np.cumsum(incr, axis=1)
    S    = np.exp(logS)                      # valeurs t1..tN
    Mmax = np.maximum(S0, S.max(axis=1))     # on inclut S0 dans le max
    disc = np.exp(-r * T) * np.maximum(Mmax - K, 0.0)
    return disc.mean(), disc.std(ddof=1) / np.sqrt(M)

Ns = [10, 50, 100, 250, 500, 1000]
prices, errs = [], []
for N in Ns:
    p, e = price_naive(N)
    prices.append(p); errs.append(e)
    print(f"N={N:5d}  prix={p:.4f}  (+/- {1.96*e:.4f})")

x = 1.0 / np.sqrt(Ns)
b, a = np.polyfit(x, prices, 1)   # prices = b*x + a
print(f"\n[Naive] Extrapolation prix continu (1/sqrt(N)->0) = {a:.4f}")


# CORRECTION PAR LE PONT BROWNIEN (N = 1)
def price_bridge(M=M, seed=1):
    rng = np.random.default_rng(seed)
    X0  = np.log(S0)
    Z   = rng.standard_normal(M)
    XT  = X0 + (r - 0.5 * sigma**2) * T + sigma * np.sqrt(T) * Z
    U   = rng.random(M)
    U   = np.clip(U, 1e-15, 1.0)             # 1-U a meme loi que U
    MX  = 0.5 * (X0 + XT + np.sqrt((XT - X0)**2 - 2 * sigma**2 * T * np.log(U)))
    Mc  = np.exp(MX)                         # maximum continu de l'actif
    disc = np.exp(-r * T) * np.maximum(Mc - K, 0.0)
    return disc.mean(), disc.std(ddof=1) / np.sqrt(M)

pb, eb = price_bridge()
print(f"[Pont brownien] prix = {pb:.4f}  IC95% = [{pb-1.96*eb:.4f} ; {pb+1.96*eb:.4f}]")

# PRIX FERME (Conze-Viswanathan) comme verite-terrain
# Cas K >= m (ici m = S0 = K)
def price_closed_form(S=S0, m=S0):
    a1 = (np.log(S / K) + (r + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
    a2 = a1 - sigma * np.sqrt(T)
    coef = sigma**2 / (2 * r)
    term = -(S / K)**(-2 * r / sigma**2) * norm.cdf(a1 - (2 * r / sigma) * np.sqrt(T)) \
           + np.exp(r * T) * norm.cdf(a1)
    return S * norm.cdf(a1) - K * np.exp(-r * T) * norm.cdf(a2) \
           + S * np.exp(-r * T) * coef * term

print(f"[Formule fermee] prix continu exact = {price_closed_form():.4f}")

# FIGURE
plt.figure(figsize=(8, 5))

plt.errorbar(x, prices, yerr=[1.96 * e for e in errs], fmt='o',
             linestyle='-',
             capsize=5, label="Prix calculé")

prix_theorique = price_closed_form()
plt.axhline(y=prix_theorique, color='r', linestyle='--', label="Prix théorique (exact)")

plt.xlabel("1 / racine(N)")
plt.ylabel("Prix de l'option")
plt.title("Convergence du prix en fonction de la discrétisation")
plt.legend()
plt.grid(True)
